void writeSocket(int fd,FCGI_Header *h,unsigned int len);
void writeLen(int len, char **p);
int addNameValuePair(FCGI_Header *h,char *name,char *value);
void sendGetValue(int fd);
void sendBeginRequest(int fd,unsigned short requestId,unsigned short role,unsigned char flags); 
void sendAbortRequest(int fd,unsigned short requestId) ;
#define sendStdin(fd,id,stdin,len) sendWebData(fd,FCGI_STDIN,id,stdin,len);
#define sendData(fd,id,data,len) sendWebData(fd,FCGI_DATA,id,data,len);
void sendWebData(int fd,unsigned char type,unsigned short requestId,char *data,unsigned int len) ;
int createSocket(int port);
